name: Bug
description: File a bug report
title: "[bug]: "
labels: ["bug", "triage"]
#assignees:
#  - 
body:
  - type: markdown
    attributes:
      value: |

        Thanks for creating a report! The issue has entered the triage (open) process. That means the issue will wait in this status until the FreePBX team has an opportunity to review the issue. Our weekly triage meetings happen every Monday. Once the issue has been reviewed you may receive comments regarding the next steps towards resolution.

        A good first step is for you to review the [FreePBX Issue Guidelines](https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10355381/FreePBX+Ticket+Reporting) if you haven't already. The guidelines detail what is expected from the FreePBX issue report.

        Then, if you are submitting a patch, please review the Patch Contribution Process.

        Please note that by submitting data, code, or documentation to Sangoma through GitHub, you accept the Terms of Use present at
        https://www.asterisk.org/terms-of-use/.
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: fpbxver
    attributes:
      label: FreePBX Version
      options:
        - FreePBX 16
        - FreePBX 17
        - FreePBX 15
        - FreePBX 13/14
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Trivial
        - Minor
        - Major
        - Critical
        - Blocker
    validations:
      required: true

  - type: input
    id: fpbxmodlist
    attributes:
      label: FreePBX modules version list
      description: Running modules version list (fwconsole ma list output)
    validations:
      required: false

  - type: dropdown
    id: modulename
    validations:
      required: true
    attributes:
      label: Affected Module
      options:
        - Framework
        - Core
        - sipsettings
        - voicemail
        - ucp
        - userman
        - certman
        - calendar
        - arimanager
        - timeconditions
        - cel
        - cdr
        - contactmanager
        - bulkhandler
        - firewall
        - pm2
        - api
        - filestore
        - amd
        - ringgroups
        - recordings
        - queues
        - paging
        - logfiles
        - ivr
        - findmefollow
        - fax
        - dashboard
        - callrecording
	- superfecta
        - hotelwakeup
        - parking
        - dahdiconfig
        - announcement
        - asterisk-cli
        - asteriskinfo
        - backup
        - blacklist
        - callback
        - callforward
        - callwaiting
        - cidlookup
        - conferences
        - customappsreg
        - daynight
        - dictate
        - digiumaddoninstaller
        - digium_phones
        - directory
        - disa
        - donotdisturb
        - dundicheck
        - extensionsettings
        - featurecodeadmin
        - iaxsettings
        - infoservices
        - languages
        - manager
        - miscapps
        - miscdests
        - music
        - outroutemsg
        - pbdirectory
        - phonebook
        - pinsets
        - printextensions
        - queueprio
        - restart
        - setcid
        - speeddial
        - tts
        - vmblast
        - weakpasswords
        - webrtc
    	- presencestate
        - cxpanel
        - soundlang
        - configedit
        - xmpp
        - ttsengines

  - type: textarea
    id: environment
    attributes:
      label: Operating Environment
      description: FreePBX Framework version, Asterisk version etc.
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: Frequency of Occurrence
      options:
        - "Never"
        - "One Time"
        - "Occasional"
        - "Frequent"
        - "Constant"
  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        [FreePBX Issue Guidelines](https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10355381/FreePBX+Ticket+Reporting) 
  - type: checkboxes
    id: guidelines
    attributes:
      label: FreePBX Issue Guidelines
      options:
        - label: Yes, I have read the FreePBX Issue Guidelines
          required: true
